package gerror

//
//import (
//"runtime"
//"strings"
//)
//
//type stack []uintptr
//
//const (
//	maxStackDepth = 32
//)
//
//func callers(skip ...int) stack {
//	var (
//		pcs [maxStackDepth]uintptr
//		n   = 3
//	)
//	if len(skip) > 0 {
//		n += skip[0]
//	}
//	return pcs[:runtime.Callers(n, pcs[:])]
//}
//
//type Error struct {
//	error error
//	Stack stack
//	Code  int    //错误码
//	Msg   string //错误信息
//	Data  any    //用于后台传递可传递数据、详细错误
//}
//
//func _new(code int, msg string, data any, skip ...int) Error {
//	err := Error{
//		Stack: nil,
//		Code:  code,
//		Msg:   msg,
//		Data:  data,
//	}
//	if len(skip) > 0 {
//		err.Stack = callers(skip[0])
//	} else {
//		err.Stack = callers()
//	}
//	return err
//}
//
//const (
//	stackFilterKey = "/errors/gerror/gerror"
//)
//
//var (
//	goRootForFilter = runtime.GOROOT()
//)
//
//func init() {
//	if goRootForFilter != "" {
//		goRootForFilter = strings.Replace(goRootForFilter, "\\", "/", -1)
//	}
//}
//func (err Error) StackRow(row int) (int, string, string) {
//	p := err.Stack[row]
//	if fn := runtime.FuncForPC(p - 1); fn != nil {
//		file, line := fn.FileLine(p - 1)
//		if strings.Contains(file, stackFilterKey) {
//			return 0, "", ""
//		}
//		// Avoid stack string like "<autogenerated>"
//		if strings.Contains(file, "<") {
//			return 0, "", ""
//		}
//		if goRootForFilter != "" && len(file) >= len(goRootForFilter) && file[0:len(goRootForFilter)] == goRootForFilter {
//			return 0, "", ""
//		}
//		return line, file, fn.Name()
//	}
//	return 0, "", ""
//}
