package gerror

import (
	"fmt"
	"path/filepath"
	"runtime"
	"strings"
)

type stack []uintptr

const maxStackDepth = 32

func callers(skip ...int) stack {
	var pcs [maxStackDepth]uintptr
	n := 3
	if len(skip) > 0 {
		n += skip[0]
	}
	cnt := runtime.Callers(n, pcs[:])
	return pcs[:cnt]
}

type Error struct {
	Cause error
	Stack stack
	Code  int
	Msg   string
	Data  any
}

const stackFilterKey = "/errors/gerror/gerror"

type Frame struct {
	File string
	Line int
	Func string
}

func (err Error) StackRow(row int) (int, string, string) {
	if row < 0 || row >= len(err.Stack) {
		return 0, "", ""
	}
	pc := err.Stack[row]
	f := runtime.FuncForPC(pc - 1)
	if f == nil {
		return 0, "", ""
	}
	file, line := f.FileLine(pc - 1)
	fn := f.Name()
	if shouldFilterFrame(file, fn) {
		return 0, "", ""
	}
	return line, filepath.ToSlash(file), fn
}

func shouldFilterFrame(file, fn string) bool {
	file = filepath.ToSlash(file)
	if strings.Contains(file, stackFilterKey) {
		return true
	}
	// 2) 避免 "<autogenerated>"
	if strings.Contains(file, "<") {
		return true
	}
	// 3) runtime/testing 这类内部包（比 GOROOT 稳定得多）
	internalPrefixes := []string{
		"runtime.",
		"reflect.",
		"testing.",
		"sync.",
		"syscall.",
	}
	for _, p := range internalPrefixes {
		if strings.HasPrefix(fn, p) {
			return true
		}
	}
	return false
}
func (err Error) Frames() []Frame {
	out := make([]Frame, 0, len(err.Stack))
	for i := 0; i < len(err.Stack); i++ {
		line, file, fn := err.StackRow(i)
		if line == 0 {
			continue
		}
		out = append(out, Frame{File: file, Line: line, Func: fn})
	}
	return out
}

func (err Error) StackString() string {
	frames := err.Frames()
	if len(frames) == 0 {
		return ""
	}
	var b strings.Builder
	for _, fr := range frames {
		// 你也可以改成更短的格式：只保留文件名
		b.WriteString(fmt.Sprintf("%s:%d %s\n", fr.File, fr.Line, fr.Func))
	}
	return b.String()
}
func (err Error) Error() string {
	if err.Msg != "" && err.Cause != nil {
		return err.Msg + ": " + err.Cause.Error()
	}
	if err.Msg != "" {
		return err.Msg
	}
	if err.Cause != nil {
		return err.Cause.Error()
	}
	return "unknown error"
}
