package field

const ID = "_id"
const IN = "$in"
const NIN = "$nin"
const NE = "$ne"
const EQ = "$eq"
const OR = "$or"
const GTE = "$gte"
const GT = "$gt"
const LTE = "$lte"
const LT = "$lt"
const Exists = "$exists"
const ElemMatch = "$elemMatch"
const Size = "$size"
